/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/CcAuthorizationMethod.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html} from 'lit-element';

import {AuthorizationMethod} from '@advanced-rest-client/authorization-method/src/AuthorizationMethod.js';

import {notifyChange} from '@advanced-rest-client/authorization-method/src/Utils.js';

export {CcAuthorizationMethod};

declare class CcAuthorizationMethod {
  readonly styles: any;
  type: any;
  readonly hasItems: Boolean|null;

  /**
   * Validates the form.
   *
   * @returns Validation result. Always true.
   */
  validate(): Boolean|null;

  /**
   * Creates a settings object with user provided data for current method.
   *
   * @returns User provided data
   */
  serialize(): object|null;

  /**
   * Restores previously serialized settings.
   * A method type must be selected before calling this function.
   *
   * @param settings Previousy serialized values.
   */
  restore(settings?: object|null): void;
  (created: any): any;
  render(): any;
}
